### ISSUE TITLE
error! - sonata bundle has been upgraded to 3.x

### ISSUE THREAD

**Issue by iBasit** [symfony-cmf/block-bundle#248]
We have latest version of sonata admin and sonata bundle.. but cmf is required old bundle..

`        "sonata-project/block-bundle": ">=2.2.12,<2.5",
`

**Comment by dbu** [comment]
happy if you can try a pull request where you allow the sonata block bundle ^3.0 as well, and then check if any tests are failing. i am not sure how good test coverage of the cmf block bundle is, it makes probably sense to try things out in the cmf sandbox or your project as well to discover if there are issues.

**Comment by iBasit** [comment]
hmm.. ok.

**Comment by iBasit** [comment]
I have added the pull request and I can start using symfony-cmf in our project and test around if there any bugs show up. 

but I really need you to get this 2.5 min requirement out of way.

**Comment by dbu** [comment]
fixed in #250

**Comment by iBasit** [comment]
Just sharing experience... 

You still have to update other required bundles that goes in chain.. installation is been fork after fork lol...

        "symfony-cmf/symfony-cmf":              "dev-master",
        "symfony-cmf/resource-rest-bundle":     "dev-master",
        "symfony-cmf/resource-bundle":          "dev-master",
        "symfony-cmf/resource":                 "dev-master",
        "sonata-project/doctrine-phpcr-admin-bundle": "dev-master", (this has tree and resource bundle)


right now installation is like journey to hell and still can't get up and running properly with existing system. But hopefully if you can linked the chain and make the installation easy.. that would be really awesome, specially for newbie.

**Comment by dbu** [comment]
using bleeding edge right now is a pain indeed, because a lot of things
are moving. but there are a couple of BC breaks to be expected anyways...

i think it would make more sense to use released stable versions. is
that broken too?

**Comment by iBasit** [comment]
Some of the bundles have requirement ^2.0 or ^1.0... (like resources bundles)

But when they don't even have any release or version tags.

**Comment by dbu** [comment]
i would recommend to go with the versions from [cmf-sandbox 1.3.0](https://github.com/symfony-cmf/cmf-sandbox/tree/1.3.0)
