### ISSUE TITLE
Only register validation metadata when PHPCR is enabled

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/block-bundle#260]

**Comment by ElectricMaxxx** [comment]
maybe we can use the routing solution as a generlized one in core-bundle and just extend with some path values from each bundle where we do need it?

**Comment by wouterj** [comment]
Don't like that very much, as it means a dep on Corebundle for each CMF bundle. Also, there are just 3 or 4 lines of code.

**Comment by ElectricMaxxx** [comment]
And i don't like code duplication that much. But the dependendency think sounds valid.

**Comment by dbu** [comment]
apart from the RoutingBundle, our bundles that need the validation depend on the core bundle anyways. @wouterj would you still go for duplication, or would it be ok to provide the compiler pass in core bundle for those bundles that depend on it anyways already?

**Comment by wouterj** [comment]
Duplicated it now in #264.

Please note that this BC break has been fixed. So we don't get this error in 3.2.1+ anymore. However, it still seems more correct to only register validation metadata when the persistence layer is enabled. Wdyt?

**Comment by dbu** [comment]
yes, it feels the right way to look at whether the storage method is active, lets keep it in.
