### ISSUE TITLE
Configure PHPCR ODM child restrictions

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/block-bundle#272]
We should implement https://github.com/doctrine/phpcr-odm/pull/706 in 2.0 of this bundle. The tree browser bundle can use this information to restrict children.

**Comment by ElectricMaxxx** [comment]
What would the task to do here then?

Add restricted Children to i.e. container block (Which one else?) 

And then? We also should enable an enhancer on the resource side to pass the data to tree-browser, right?
